services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql-auditoria
    environment:
      - 'MYSQL_DATABASE=auditoria_db'
      - 'MYSQL_PASSWORD=auditoria123'
      - 'MYSQL_ROOT_PASSWORD=root123'
      - 'MYSQL_USER=auditoria_user'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: mailhog-auditoria
    ports:
      - '1026:1025'  # SMTP server
      - '8026:8025'  # Web UI
    restart: unless-stopped

volumes:
  mysql_data:
